const userData = {
    "login": "ryantheshort",
    "id": 112423383,
    "node_id": "U_kgDOBrNx1w",
    "avatar_url": "https://avatars.githubusercontent.com/u/112423383?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ryantheshort",
    "html_url": "https://github.com/ryantheshort",
    "followers_url": "https://api.github.com/users/ryantheshort/followers",
    "following_url": "https://api.github.com/users/ryantheshort/following{/other_user}",
    "gists_url": "https://api.github.com/users/ryantheshort/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ryantheshort/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ryantheshort/subscriptions",
    "organizations_url": "https://api.github.com/users/ryantheshort/orgs",
    "repos_url": "https://api.github.com/users/ryantheshort/repos",
    "events_url": "https://api.github.com/users/ryantheshort/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ryantheshort/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Ryan Short",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 12,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2022-08-29T18:03:54Z",
    "updated_at": "2022-09-19T16:18:10Z"
  }